"""Remove content_url from courses

Revision ID: 611fccbcd46d
Revises: 55850e6df37c
Create Date: 2026-07-22 19:15:49.518234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611fccbcd46d'
down_revision: Union[str, Sequence[str], None] = '55850e6df37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('courses', 'content_url')
    op.alter_column('lessons', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('courses', sa.Column('content_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
   
    # ### end Alembic commands ###
